### ISSUE TITLE
sfx.h generating error

### ISSUE THREAD

**Issue by silverdr** [bboxy/bitfire#9]
When trying to build zx0, an `sfx.h` file is generated. This file seems to be corrupted due to erroneous newline `\n` handling I believe. The resulting file contains corrupt data like:
```
./sfx.h:7:55: error: use of undeclared identifier 'n0x31'
    0x01,0x08,0x0b,0x08,0x42,0x06,0x9e,0x32,0x30,0x36,n0x31,0x00,0x00,0x00,0x78,0xe6,0x01,0xa5,0xba,0x48,n0xa2,0xd0,0xbd,0x3...
                                                      ^
```
This happens when trying to compile under macOS 10,14.6

**Comment by silverdr** [comment]
This seems to be caused by the old neverending story of `gnu-sed vs. bsd-sed`. It should theoretically be possible to use common / POSIX sed commands to achieve the same results but I am still far from being a good enough `sed` wizard to send a PR with that

**Comment by bboxy** [comment]
Thanks for spotting that, i will try to find a sed command that will satisfy both seds.

**Comment by bboxy** [comment]
I guess i fixed it now by first replacing a newline with a bogus char and then finally replacing it with a \n via tr. I have other occurrences of sed with newlines in the macro-generation script. Might have to fix that too. So far i hope the build works.

**Comment by silverdr** [comment]
Thank you for taking care of this. I'll take a fresh clone, check and report.

**Comment by silverdr** [comment]
There is an improvement. The `decruncher` array is now correct, albeit not indented (except first line). But the `#define`s on top of the file are still broken (that's another `sed` invocation). See below (can't attach file without renaming so here it goes).
```
#define 	ZX0_DATA_SIZE_HI	= $1f
#define 	ZX0_DST	= $8b
#define 	ZX0_SFX_ADDR	= $104
#define 	ZX0_DATA_END	= $22
#define 	ZX0_SRC	= $43
static const char decruncher[] = {
    0x01,0x08,0x0b,0x08,0x42,0x06,0x9e,0x32,0x30,0x36,
0x31,0x00,0x00,0x00,0x78,0xe6,0x01,0xa5,0xba,0x48,
0xa2,0xd0,0xbd,0x34,0x08,0x95,0x01,0xca,0xd0,0xf8,
0xa0,0x00,0xca,0xbd,0x05,0x08,0x9d,0x00,0xff,0x8a,
0xd0,0xf6,0xce,0x22,0x08,0xce,0x25,0x08,0x88,0xd0,
0xed,0x4c,0x02,0x00,0xa9,0x01,0x06,0xa3,0xb0,0x6a,
0x20,0xb8,0x00,0xaa,0xf0,0x5d,0xb9,0x05,0x09,0x91,
0x57,0xc8,0xca,0xd0,0xf7,0x88,0x98,0x65,0x57,0x85,
0x57,0x90,0x02,0xe6,0x58,0x98,0x38,0x65,0x0f,0x85,
0x0f,0x90,0x02,0xe6,0x10,0xa4,0x5f,0xd0,0x39,0xa9,
0x01,0x06,0xa3,0xb0,0x3d,0x20,0xb8,0x00,0xe9,0x01,
0x38,0x49,0xff,0xa8,0x49,0xff,0x65,0x57,0x85,0x57,
0xb0,0x02,0xc6,0x58,0x18,0xe9,0x00,0x85,0x54,0xa5,
0x58,0xe9,0x00,0x85,0x55,0xb9,0xef,0xbe,0x99,0x00,
0x40,0xc8,0xd0,0xf7,0xe6,0x58,0xa9,0x00,0xf0,0xa0,
0xc6,0x5f,0xe6,0x55,0xd0,0xeb,0x38,0xa0,0x00,0xc6,
0x5f,0xb0,0x9f,0x06,0xa3,0x2a,0x06,0xa3,0x90,0xf9,
0xd0,0x03,0x20,0xa4,0x00,0xe9,0x01,0x90,0x49,0x4a,
0x85,0x50,0xb1,0x0f,0x6a,0x85,0x4a,0xe6,0x0f,0xd0,
0x02,0xe6,0x10,0xa9,0x01,0xa0,0xfe,0xb0,0xad,0x06,
0xa3,0x2a,0x06,0xa3,0x90,0xf9,0xd0,0x9f,0xa0,0x00,
0x20,0xa4,0x00,0xb0,0x98,0x40,0xaa,0xb1,0x0f,0x2a,
0x85,0xa3,0xe6,0x0f,0xd0,0x02,0xe6,0x10,0x8a,0xb0,
0x14,0x06,0xa3,0x2a,0xb0,0x07,0x06,0xa3,0x90,0xf7,
0xf0,0xe6,0x60,0x48,0x98,0x20,0xb5,0x00,0x85,0x5f,
0x68,0x60,0xc6,0x01,0x84,0x98,0x68,0x85,0xba,0x4c,
0x00,0x00
};
```

**Comment by bboxy** [comment]
There was a \s instead of [[:space:]] in the defines sed, should work now too, also identation should be fixed. Looks good here at least, but have no means to check against bsd :-/

**Comment by silverdr** [comment]
I can confirm that the generated file is now both indented (with spaces instead of tabs ;-) and free of errors. Thank you very much for fixing this.

**Comment by silverdr** [comment]
Here is how it looks now:
```
#define ZX0_DATA_SIZE_HI 0x1f
#define ZX0_DST 0x8b
#define ZX0_SFX_ADDR 0x104
#define ZX0_DATA_END 0x22
#define ZX0_SRC 0x43
static const char decruncher[] = {
    0x01,0x08,0x0b,0x08,0x42,0x06,0x9e,0x32,0x30,0x36,
    0x31,0x00,0x00,0x00,0x78,0xe6,0x01,0xa5,0xba,0x48,
    0xa2,0xd0,0xbd,0x34,0x08,0x95,0x01,0xca,0xd0,0xf8,
    0xa0,0x00,0xca,0xbd,0x05,0x08,0x9d,0x00,0xff,0x8a,
    0xd0,0xf6,0xce,0x22,0x08,0xce,0x25,0x08,0x88,0xd0,
    0xed,0x4c,0x02,0x00,0xa9,0x01,0x06,0xa3,0xb0,0x6a,
    0x20,0xb8,0x00,0xaa,0xf0,0x5d,0xb9,0x05,0x09,0x91,
    0x57,0xc8,0xca,0xd0,0xf7,0x88,0x98,0x65,0x57,0x85,
    0x57,0x90,0x02,0xe6,0x58,0x98,0x38,0x65,0x0f,0x85,
    0x0f,0x90,0x02,0xe6,0x10,0xa4,0x5f,0xd0,0x39,0xa9,
    0x01,0x06,0xa3,0xb0,0x3d,0x20,0xb8,0x00,0xe9,0x01,
    0x38,0x49,0xff,0xa8,0x49,0xff,0x65,0x57,0x85,0x57,
    0xb0,0x02,0xc6,0x58,0x18,0xe9,0x00,0x85,0x54,0xa5,
    0x58,0xe9,0x00,0x85,0x55,0xb9,0xef,0xbe,0x99,0x00,
    0x40,0xc8,0xd0,0xf7,0xe6,0x58,0xa9,0x00,0xf0,0xa0,
    0xc6,0x5f,0xe6,0x55,0xd0,0xeb,0x38,0xa0,0x00,0xc6,
    0x5f,0xb0,0x9f,0x06,0xa3,0x2a,0x06,0xa3,0x90,0xf9,
    0xd0,0x03,0x20,0xa4,0x00,0xe9,0x01,0x90,0x49,0x4a,
    0x85,0x50,0xb1,0x0f,0x6a,0x85,0x4a,0xe6,0x0f,0xd0,
    0x02,0xe6,0x10,0xa9,0x01,0xa0,0xfe,0xb0,0xad,0x06,
    0xa3,0x2a,0x06,0xa3,0x90,0xf9,0xd0,0x9f,0xa0,0x00,
    0x20,0xa4,0x00,0xb0,0x98,0x40,0xaa,0xb1,0x0f,0x2a,
    0x85,0xa3,0xe6,0x0f,0xd0,0x02,0xe6,0x10,0x8a,0xb0,
    0x14,0x06,0xa3,0x2a,0xb0,0x07,0x06,0xa3,0x90,0xf7,
    0xf0,0xe6,0x60,0x48,0x98,0x20,0xb5,0x00,0x85,0x5f,
    0x68,0x60,0xc6,0x01,0x84,0x98,0x68,0x85,0xba,0x4c,
    0x00,0x00
};
```

**Comment by bboxy** [comment]
The four spaces are desired, as it is header-file for the c-source of the zx0 packer :-) Indentation was broken due to the newlines missing in that stage due to the sed changes :-)

**Comment by silverdr** [comment]
> The four spaces are desired, as it is header-file for the c-source of the zx0 packer :-)

I know what this is. I was just pulling your leg about tabs vs. spaces. :-P

**Comment by bboxy** [comment]
you!!!! should not do that without a pull-request!1! :-P
